# Generated by Django 3.2.9 on 2022-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_url_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(help_text='Введите ссылку', unique=True, verbose_name='Ссылка'),
        ),
    ]
